.

diff --git a/.github/workflows/MasterPipeline_autoHeal.yml b/.github/workflows/MasterPipeline_autoHeal.yml
--- a/.github/workflows/MasterPipeline_autoHeal.yml
+++ b/.github/workflows/MasterPipeline_autoHeal.yml
@@ -227,7 +227,7 @@ jobs:
 
           else
             echo "➡ Running sequentially"
-            python -m pytest $TEST_ARGS SRC\tests\tests_ui\test_login.py --jira-xray --client-secret-auth --cloud -v --junitxml=test-results.xml --json-report --json-report-file=test-results.json || echo "TEST_FAILED=1" >> $GITHUB_ENV
+            python -m pytest $TEST_ARGS --jira-xray --client-secret-auth --cloud -v --junitxml=test-results.xml --json-report --json-report-file=test-results.json || echo "TEST_FAILED=1" >> $GITHUB_ENV
           fi
 
 
